[workspace]
resolver = "2"
members = [
    # tidy-alphabetical-start
    "compiler/tidec", "compiler/tidec_codgen_llvm",
    "compiler/tidec_lir",
    "compiler/tidec_utils",
    # tidy-alphabetical-end
]
