[package]
name = "tidec_tir"
version = "0.1.0"
edition = "2021"

[dependencies]
# tidy-alphabetical-start
tidec_abi = { path = "../tidec_abi" }
tidec_utils = { path = "../tidec_utils" }
tracing = "0.1.41"
# tidy-alphabetical-end
